export type AvatarOption = {
  id: string;
  label: string;
  src: string;
};

const AVATAR_FILENAMES = [
  "AJ Styles.jpeg",
  "anna.jpeg",
  "anna1.jpeg",
  "annie.jpeg",
  "armin.jpg",
  "armin1.jpeg",
  "asta.jpeg",
  "asta1.jpeg",
  "asuna yuki1.jpeg",
  "asuna yuuki.jpeg",
  "attack titan.jpeg",
  "babar azam.jpeg",
  "baburao.jpeg",
  "batman1.jpeg",
  "batman2.jpeg",
  "batman3.jpeg",
  "Ben Stokes.jpeg",
  "ben10.jpeg",
  "Big Show.jpeg",
  "Brock Lesnar.jpeg",
  "buttercup.jpeg",
  "CHARLES LECLERC.jpeg",
  "chisiya.jpeg",
  "cleo.jpeg",
  "colossus titan.jpeg",
  "connie.jpeg",
  "cristiano ronaldo.jpeg",
  "Daenerys Targaryen.jpeg",
  "demogorgon.jpeg",
  "dhoni.jpeg",
  "Doctor Strange.jpeg",
  "Dolf ZIGgler.jpeg",
  "doremon.jpg",
  "Dr.Alexei.jpeg",
  "DR_STRANGE 1.jpeg",
  "dr_strange.jpg",
  "dustin.jpeg",
  "dustin1.jpeg",
  "Eddie.jpeg",
  "el.jpeg",
  "elsa.jpeg",
  "elsa1.jpeg",
  "eren.jpg",
  "eren1.jpeg",
  "eren2.jpeg",
  "erwin.jpeg",
  "erza scarlet.jpeg",
  "female titan.jpeg",
  "fuchhey.jpeg",
  "furina.jpeg",
  "furina2.jpeg",
  "Gabbar.jpeg",
  "Gi hun.jpeg",
  "hangezoe.jpeg",
  "hattori.jpg",
  "hinata hyuga.jpeg",
  "hinata1.jpeg",
  "hopper.jpeg",
  "hulk.jpg",
  "hulk1.jpeg",
  "hulk2.jpeg",
  "hulku.jpeg",
  "inosuke.jpeg",
  "inosuke1.jpeg",
  "iron_man.jpg",
  "ironman.jpeg",
  "ironman1.jpeg",
  "IShowSpeed.jpeg",
  "IShowSpeed1.jpeg",
  "Itachi Uchiha.jpeg",
  "itachi.jpeg",
  "John Cena.jpeg",
  "johncena.jpeg",
  "jon snow.jpeg",
  "Kim Possible.jpeg",
  "kroos.jpeg",
  "kuchupuchu.jpeg",
  "L Lawliet.jpeg",
  "L lawliet1.gif",
  "L.jpg",
  "lamine yamal.jpeg",
  "lamine2.jpeg",
  "levi.jpg",
  "levi1.jpeg",
  "light yagami.jpeg",
  "lisa simpson.jpeg",
  "lisho.jpeg",
  "loki.jpg",
  "Lucas Sinclair.jpeg",
  "Luffy.jpeg",
  "luffy1.jpeg",
  "Luka Modrić.jpeg",
  "mabel pines.jpeg",
  "maci.jpeg",
  "Madara Uchiha.jpeg",
  "makkhan chor.jpeg",
  "manjulika.jpeg",
  "manohar.jpeg",
  "manohar1.jpeg",
  "maradona.jpeg",
  "Marco.jpeg",
  "margesimpson.jpeg",
  "Max Mayfield.jpeg",
  "mbapppe.jpeg",
  "merla.jpeg",
  "messi miami.jpeg",
  "messi.jpeg",
  "messi1.jpeg",
  "messibarca.jpeg",
  "mikasa.jpeg",
  "mikasa.jpg",
  "mikasa2.jpeg",
  "mikasa4.jpeg",
  "mike.jpeg",
  "misamisa.jpeg",
  "Mitsuri Kanroji.jpeg",
  "Mitsuri Kanroji1.jpeg",
  "mitsuri.jpeg",
  "Mohamed Salah.jpeg",
  "mona.jpeg",
  "mr beast.jpeg",
  "ms dhoni.jpeg",
  "Muzan Kibutsuji.jpeg",
  "nami.jpeg",
  "nami1.jpeg",
  "nancy.jpeg",
  "neymar jr.jpeg",
  "nezuko.jpeg",
  "nezuko12.jpeg",
  "ninja.jpeg",
  "niragi.jpeg",
  "Obito Uchiha.jpeg",
  "prabhas.jpeg",
  "pushpa.jpeg",
  "Ranbir kapoor.jpeg",
  "rasmalai.jpeg",
  "Raven.jpeg",
  "reiner.jpeg",
  "rem.jpeg",
  "rem1.jpeg",
  "Rey misterio.jpeg",
  "Ricardo kaká.jpeg",
  "Robert Lewandowksi.jpeg",
  "Robin.gif",
  "rocky bhai.jpeg",
  "Rohit Sharma.jpeg",
  "Roman Reigns.jpeg",
  "ronaldo.jpeg",
  "Ryuk 1.jpeg",
  "Ryuk.jpeg",
  "Ryuk2.jpeg",
  "Saitama.jpeg",
  "sakura.jpeg",
  "sarah.jpeg",
  "sasha.jpeg",
  "sasuke.jpeg",
  "Sheamus.jpeg",
  "shekhawat.jpeg",
  "Shinobu kocho.jpeg",
  "siderman 2.jpeg",
  "SM.jpeg",
  "SM1.jpeg",
  "SM18(1).jpeg",
  "SM18.jpeg",
  "SM2.jpeg",
  "spider_man.jpg",
  "spiderman.jpeg",
  "spiderman3.jpeg",
  "Starfire.gif",
  "Steve.jpeg",
  "steve2.jpeg",
  "superman.jpeg",
  "superman2.jpeg",
  "Tamayo.jpeg",
  "tamayo1.jpeg",
  "Tanjiro.jpeg",
  "tanjiro1.jpeg",
  "thalapathy vijay.jpeg",
  "thalapathy.jpeg",
  "thanos.jpeg",
  "the beast.jpeg",
  "Thor.jpeg",
  "thor1.jpeg",
  "tokito.jpeg",
  "kane.jpeg",
  "Vecna.jpeg",
  "vecna1.jpeg",
  "venom.jpeg",
  "virat kohli.jpeg",
  "virus.jpeg",
  "will.jpeg",
  "yoriichi.jpeg",
  "yuji.jpeg",
  "Zenitsu Agatsuma.jpeg",
  "Zenitsu chibi.jpeg",
  "ZERO TWO.jpeg",
  "zoro.jpeg",
  "zoro1.jpeg",
  "Nezuko Kamado.jpeg",
  "Hange Zoe (1).jpeg",
  "Levi Ackerman.jpeg",
] as const;

function stripExtension(filename: string) {
  return filename.replace(/\.[^/.]+$/, "");
}

export const AVATAR_OPTIONS: AvatarOption[] = AVATAR_FILENAMES.map(
  (filename) => ({
    id: filename,
    label: stripExtension(filename),
    src: encodeURI(`/avatars/${filename}`),
  })
);
